import { MigrationInterface, QueryRunner } from "typeorm";

export class PrimeiraMigracao1749826421073 implements MigrationInterface {
    name = 'PrimeiraMigracao1749826421073'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`endereco\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`cep\` varchar(100) NULL, \`uf\` enum ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NULL, \`localidade\` varchar(100) NULL, \`bairro\` varchar(100) NULL, \`logradouro\` varchar(100) NULL, \`numero\` varchar(100) NULL, \`complemento\` varchar(255) NULL DEFAULT '', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`telefone\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`ddd\` varchar(255) NOT NULL, \`numero\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`fornecedor\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`nome\` varchar(100) NOT NULL, \`enderecoId\` bigint NULL, UNIQUE INDEX \`REL_6e18d94ebc5a941f02a63c5c49\` (\`enderecoId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`produto\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`nome\` varchar(100) NOT NULL, \`codigo\` varchar(100) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cliente\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`old_id\` int NULL, \`possivel_cliente\` tinyint NOT NULL DEFAULT 0, \`nome\` varchar(100) NOT NULL, \`cnpj\` varchar(100) NULL, \`email\` varchar(100) NULL, \`ddd\` varchar(255) NOT NULL, \`telefone_principal\` varchar(255) NOT NULL, \`preferencia_horario\` time NULL, \`aniversario\` date NULL, \`primeiro_contato\` date NULL, \`ultimo_contato\` datetime NULL, \`proximo_contato\` date NULL, \`data_fundacao\` date NULL, \`origem\` varchar(150) NULL, \`obs\` varchar(512) NULL, \`contato\` varchar(255) NULL, \`contato2\` varchar(255) NULL, \`contato3\` varchar(255) NULL, \`concorrente\` varchar(255) NULL, \`usuarioId\` bigint NULL, \`enderecoId\` bigint NULL, UNIQUE INDEX \`REL_b3e53e9c65f1a58088bb28c4db\` (\`enderecoId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`venda\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`clienteId\` bigint NULL, \`usuarioId\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transferencia-cliente\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`clienteId\` bigint NULL, \`movitoPorId\` bigint NULL, \`movitoDeId\` bigint NULL, \`movitoParaId\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permissao\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`resource\` enum ('ENDERECO', 'USUARIO', 'PERMISSION') NOT NULL, \`action\` enum ('CREATE', 'READ', 'UPDATE', 'SOFTDELETE', 'DELETE') NOT NULL, \`usuarioId\` bigint NOT NULL, UNIQUE INDEX \`IDX_318d80ec9b2e2c4a7d01552917\` (\`resource\`, \`action\`, \`usuarioId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`funil\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`nome\` varchar(100) NOT NULL, \`descricao\` varchar(100) NULL, \`cor\` varchar(100) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`perda\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`observacao\` varchar(100) NULL, \`clienteId\` bigint NULL, \`usuarioId\` bigint NULL, \`funilId\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ocorrencia-flag\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`nome\` varchar(100) NOT NULL, \`cor\` varchar(100) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ocorrencia\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`nome\` varchar(100) NOT NULL, UNIQUE INDEX \`IDX_82637440f03498f3c6e241000d\` (\`nome\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`metricas_usuario\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`duracao_segundos\` float NOT NULL DEFAULT '0', \`usuarioId\` bigint NULL, \`ocorrenciaId\` bigint NULL, UNIQUE INDEX \`usuario-ocorrencia\` (\`usuarioId\`, \`ocorrenciaId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`logs\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`error\` json NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`agendamento\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`date\` date NOT NULL, \`time\` time NOT NULL, \`clienteId\` bigint NULL, \`usuarioId\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contato\` (\`id\` bigint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`inicio\` datetime NULL, \`fim\` datetime NULL, \`observacao\` varchar(255) NULL, \`usuarioId\` bigint NULL, \`clienteId\` bigint NULL, \`funilId\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`fornecedor_telefones_telefone\` (\`fornecedorId\` bigint NOT NULL, \`telefoneId\` bigint NOT NULL, INDEX \`IDX_ed9e8389af4c7f0cc00384f81f\` (\`fornecedorId\`), INDEX \`IDX_f1509cffb191ea48e42ba47e65\` (\`telefoneId\`), PRIMARY KEY (\`fornecedorId\`, \`telefoneId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`produto_fornecedores_fornecedor\` (\`produtoId\` bigint NOT NULL, \`fornecedorId\` bigint NOT NULL, INDEX \`IDX_82dad16f5b419d515e65a69fb6\` (\`produtoId\`), INDEX \`IDX_02315821f911701cc643ddd6bc\` (\`fornecedorId\`), PRIMARY KEY (\`produtoId\`, \`fornecedorId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cliente_produtos_produto\` (\`clienteId\` bigint NOT NULL, \`produtoId\` bigint NOT NULL, INDEX \`IDX_8cd9bce9e1ac682b4c4f66cd56\` (\`clienteId\`), INDEX \`IDX_44b282ee52a4ec03f3cb6a9acf\` (\`produtoId\`), PRIMARY KEY (\`clienteId\`, \`produtoId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cliente_telefones_telefone\` (\`clienteId\` bigint NOT NULL, \`telefoneId\` bigint NOT NULL, INDEX \`IDX_d6b14fb9e3c12f9d1add2a806e\` (\`clienteId\`), INDEX \`IDX_9d38fe4f4983383976e86cd2e5\` (\`telefoneId\`), PRIMARY KEY (\`clienteId\`, \`telefoneId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`venda_produtos_produto\` (\`vendaId\` bigint NOT NULL, \`produtoId\` bigint NOT NULL, INDEX \`IDX_54718795de3c5cb781eea09819\` (\`vendaId\`), INDEX \`IDX_8976a3faa1be5c9bad1591c104\` (\`produtoId\`), PRIMARY KEY (\`vendaId\`, \`produtoId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`perda_produtos_produto\` (\`perdaId\` bigint NOT NULL, \`produtoId\` bigint NOT NULL, INDEX \`IDX_d8931ba4b2b0ac61023b6c05a8\` (\`perdaId\`), INDEX \`IDX_33871093b92a531e2dd94b973b\` (\`produtoId\`), PRIMARY KEY (\`perdaId\`, \`produtoId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ocorrencia_flags_ocorrencia-flag\` (\`ocorrenciaId\` bigint NOT NULL, \`ocorrenciaFlagId\` bigint NOT NULL, INDEX \`IDX_1fa6e78bfb74cfc6ade35d8a2b\` (\`ocorrenciaId\`), INDEX \`IDX_93efba0a2c38d6a4ee0da268cf\` (\`ocorrenciaFlagId\`), PRIMARY KEY (\`ocorrenciaId\`, \`ocorrenciaFlagId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contato_ocorrencias_ocorrencia\` (\`contatoId\` bigint NOT NULL, \`ocorrenciaId\` bigint NOT NULL, INDEX \`IDX_7cd69c4ccf4db31b801110a7c4\` (\`contatoId\`), INDEX \`IDX_4056175fea64c465a8785d7789\` (\`ocorrenciaId\`), PRIMARY KEY (\`contatoId\`, \`ocorrenciaId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contato_produtos_produto\` (\`contatoId\` bigint NOT NULL, \`produtoId\` bigint NOT NULL, INDEX \`IDX_9a697c7f2dace62a85557da34f\` (\`contatoId\`), INDEX \`IDX_52c649a8d3e70b66cabf774259\` (\`produtoId\`), PRIMARY KEY (\`contatoId\`, \`produtoId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`email\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD UNIQUE INDEX \`IDX_2863682842e688ca198eb25c12\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`senha\` varchar(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`role\` enum ('DEV', 'ADMIN', 'GERENTE', 'FUNCIONARIO') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`id\` bigint NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`nome\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`nome\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`fornecedor\` ADD CONSTRAINT \`FK_6e18d94ebc5a941f02a63c5c49a\` FOREIGN KEY (\`enderecoId\`) REFERENCES \`endereco\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cliente\` ADD CONSTRAINT \`FK_26eb6132b607fd16d904df0367d\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cliente\` ADD CONSTRAINT \`FK_b3e53e9c65f1a58088bb28c4dbe\` FOREIGN KEY (\`enderecoId\`) REFERENCES \`endereco\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`venda\` ADD CONSTRAINT \`FK_15b70438372ffad25249a2c6fec\` FOREIGN KEY (\`clienteId\`) REFERENCES \`cliente\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`venda\` ADD CONSTRAINT \`FK_fd83d651fb05d24bc1e97c4cff6\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transferencia-cliente\` ADD CONSTRAINT \`FK_aa1ee04e3254cb73f40bde418e1\` FOREIGN KEY (\`clienteId\`) REFERENCES \`cliente\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transferencia-cliente\` ADD CONSTRAINT \`FK_a7dcfff24a872d32abb3c474cc6\` FOREIGN KEY (\`movitoPorId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transferencia-cliente\` ADD CONSTRAINT \`FK_265743ae329bde2b9a2fcc89a73\` FOREIGN KEY (\`movitoDeId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transferencia-cliente\` ADD CONSTRAINT \`FK_02cf22c3bf09af4d9d0e069a7b4\` FOREIGN KEY (\`movitoParaId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permissao\` ADD CONSTRAINT \`FK_c0b320e1b0943f7f0996678fecd\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`perda\` ADD CONSTRAINT \`FK_1796ebd4e5cc641dfc669a74110\` FOREIGN KEY (\`clienteId\`) REFERENCES \`cliente\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`perda\` ADD CONSTRAINT \`FK_8a1a5d43b168400bec3070b41d9\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`perda\` ADD CONSTRAINT \`FK_67e63d84cb42f0a7b817c8890b5\` FOREIGN KEY (\`funilId\`) REFERENCES \`funil\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`metricas_usuario\` ADD CONSTRAINT \`FK_999f6cf6d7f32b70bed76877eb0\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`metricas_usuario\` ADD CONSTRAINT \`FK_12396865edb43183576142fddc5\` FOREIGN KEY (\`ocorrenciaId\`) REFERENCES \`ocorrencia\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agendamento\` ADD CONSTRAINT \`FK_ad85077023b774f9e4d88b2cee8\` FOREIGN KEY (\`clienteId\`) REFERENCES \`cliente\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agendamento\` ADD CONSTRAINT \`FK_13ec81c13705678cfa80c18b1fa\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contato\` ADD CONSTRAINT \`FK_9d90f21eeab241427e4e4b9b8a4\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contato\` ADD CONSTRAINT \`FK_b86a0f00baf92fadc0ef81da030\` FOREIGN KEY (\`clienteId\`) REFERENCES \`cliente\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contato\` ADD CONSTRAINT \`FK_26d882031496f13dc69f2c4dbe3\` FOREIGN KEY (\`funilId\`) REFERENCES \`funil\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fornecedor_telefones_telefone\` ADD CONSTRAINT \`FK_ed9e8389af4c7f0cc00384f81fc\` FOREIGN KEY (\`fornecedorId\`) REFERENCES \`fornecedor\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`fornecedor_telefones_telefone\` ADD CONSTRAINT \`FK_f1509cffb191ea48e42ba47e654\` FOREIGN KEY (\`telefoneId\`) REFERENCES \`telefone\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`produto_fornecedores_fornecedor\` ADD CONSTRAINT \`FK_82dad16f5b419d515e65a69fb6b\` FOREIGN KEY (\`produtoId\`) REFERENCES \`produto\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`produto_fornecedores_fornecedor\` ADD CONSTRAINT \`FK_02315821f911701cc643ddd6bc9\` FOREIGN KEY (\`fornecedorId\`) REFERENCES \`fornecedor\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cliente_produtos_produto\` ADD CONSTRAINT \`FK_8cd9bce9e1ac682b4c4f66cd56f\` FOREIGN KEY (\`clienteId\`) REFERENCES \`cliente\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cliente_produtos_produto\` ADD CONSTRAINT \`FK_44b282ee52a4ec03f3cb6a9acf5\` FOREIGN KEY (\`produtoId\`) REFERENCES \`produto\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cliente_telefones_telefone\` ADD CONSTRAINT \`FK_d6b14fb9e3c12f9d1add2a806e2\` FOREIGN KEY (\`clienteId\`) REFERENCES \`cliente\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cliente_telefones_telefone\` ADD CONSTRAINT \`FK_9d38fe4f4983383976e86cd2e53\` FOREIGN KEY (\`telefoneId\`) REFERENCES \`telefone\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`venda_produtos_produto\` ADD CONSTRAINT \`FK_54718795de3c5cb781eea098193\` FOREIGN KEY (\`vendaId\`) REFERENCES \`venda\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`venda_produtos_produto\` ADD CONSTRAINT \`FK_8976a3faa1be5c9bad1591c1048\` FOREIGN KEY (\`produtoId\`) REFERENCES \`produto\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`perda_produtos_produto\` ADD CONSTRAINT \`FK_d8931ba4b2b0ac61023b6c05a8f\` FOREIGN KEY (\`perdaId\`) REFERENCES \`perda\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`perda_produtos_produto\` ADD CONSTRAINT \`FK_33871093b92a531e2dd94b973bd\` FOREIGN KEY (\`produtoId\`) REFERENCES \`produto\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`ocorrencia_flags_ocorrencia-flag\` ADD CONSTRAINT \`FK_1fa6e78bfb74cfc6ade35d8a2b9\` FOREIGN KEY (\`ocorrenciaId\`) REFERENCES \`ocorrencia\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`ocorrencia_flags_ocorrencia-flag\` ADD CONSTRAINT \`FK_93efba0a2c38d6a4ee0da268cf1\` FOREIGN KEY (\`ocorrenciaFlagId\`) REFERENCES \`ocorrencia-flag\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`contato_ocorrencias_ocorrencia\` ADD CONSTRAINT \`FK_7cd69c4ccf4db31b801110a7c4c\` FOREIGN KEY (\`contatoId\`) REFERENCES \`contato\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`contato_ocorrencias_ocorrencia\` ADD CONSTRAINT \`FK_4056175fea64c465a8785d77898\` FOREIGN KEY (\`ocorrenciaId\`) REFERENCES \`ocorrencia\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`contato_produtos_produto\` ADD CONSTRAINT \`FK_9a697c7f2dace62a85557da34f4\` FOREIGN KEY (\`contatoId\`) REFERENCES \`contato\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`contato_produtos_produto\` ADD CONSTRAINT \`FK_52c649a8d3e70b66cabf7742594\` FOREIGN KEY (\`produtoId\`) REFERENCES \`produto\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`contato_produtos_produto\` DROP FOREIGN KEY \`FK_52c649a8d3e70b66cabf7742594\``);
        await queryRunner.query(`ALTER TABLE \`contato_produtos_produto\` DROP FOREIGN KEY \`FK_9a697c7f2dace62a85557da34f4\``);
        await queryRunner.query(`ALTER TABLE \`contato_ocorrencias_ocorrencia\` DROP FOREIGN KEY \`FK_4056175fea64c465a8785d77898\``);
        await queryRunner.query(`ALTER TABLE \`contato_ocorrencias_ocorrencia\` DROP FOREIGN KEY \`FK_7cd69c4ccf4db31b801110a7c4c\``);
        await queryRunner.query(`ALTER TABLE \`ocorrencia_flags_ocorrencia-flag\` DROP FOREIGN KEY \`FK_93efba0a2c38d6a4ee0da268cf1\``);
        await queryRunner.query(`ALTER TABLE \`ocorrencia_flags_ocorrencia-flag\` DROP FOREIGN KEY \`FK_1fa6e78bfb74cfc6ade35d8a2b9\``);
        await queryRunner.query(`ALTER TABLE \`perda_produtos_produto\` DROP FOREIGN KEY \`FK_33871093b92a531e2dd94b973bd\``);
        await queryRunner.query(`ALTER TABLE \`perda_produtos_produto\` DROP FOREIGN KEY \`FK_d8931ba4b2b0ac61023b6c05a8f\``);
        await queryRunner.query(`ALTER TABLE \`venda_produtos_produto\` DROP FOREIGN KEY \`FK_8976a3faa1be5c9bad1591c1048\``);
        await queryRunner.query(`ALTER TABLE \`venda_produtos_produto\` DROP FOREIGN KEY \`FK_54718795de3c5cb781eea098193\``);
        await queryRunner.query(`ALTER TABLE \`cliente_telefones_telefone\` DROP FOREIGN KEY \`FK_9d38fe4f4983383976e86cd2e53\``);
        await queryRunner.query(`ALTER TABLE \`cliente_telefones_telefone\` DROP FOREIGN KEY \`FK_d6b14fb9e3c12f9d1add2a806e2\``);
        await queryRunner.query(`ALTER TABLE \`cliente_produtos_produto\` DROP FOREIGN KEY \`FK_44b282ee52a4ec03f3cb6a9acf5\``);
        await queryRunner.query(`ALTER TABLE \`cliente_produtos_produto\` DROP FOREIGN KEY \`FK_8cd9bce9e1ac682b4c4f66cd56f\``);
        await queryRunner.query(`ALTER TABLE \`produto_fornecedores_fornecedor\` DROP FOREIGN KEY \`FK_02315821f911701cc643ddd6bc9\``);
        await queryRunner.query(`ALTER TABLE \`produto_fornecedores_fornecedor\` DROP FOREIGN KEY \`FK_82dad16f5b419d515e65a69fb6b\``);
        await queryRunner.query(`ALTER TABLE \`fornecedor_telefones_telefone\` DROP FOREIGN KEY \`FK_f1509cffb191ea48e42ba47e654\``);
        await queryRunner.query(`ALTER TABLE \`fornecedor_telefones_telefone\` DROP FOREIGN KEY \`FK_ed9e8389af4c7f0cc00384f81fc\``);
        await queryRunner.query(`ALTER TABLE \`contato\` DROP FOREIGN KEY \`FK_26d882031496f13dc69f2c4dbe3\``);
        await queryRunner.query(`ALTER TABLE \`contato\` DROP FOREIGN KEY \`FK_b86a0f00baf92fadc0ef81da030\``);
        await queryRunner.query(`ALTER TABLE \`contato\` DROP FOREIGN KEY \`FK_9d90f21eeab241427e4e4b9b8a4\``);
        await queryRunner.query(`ALTER TABLE \`agendamento\` DROP FOREIGN KEY \`FK_13ec81c13705678cfa80c18b1fa\``);
        await queryRunner.query(`ALTER TABLE \`agendamento\` DROP FOREIGN KEY \`FK_ad85077023b774f9e4d88b2cee8\``);
        await queryRunner.query(`ALTER TABLE \`metricas_usuario\` DROP FOREIGN KEY \`FK_12396865edb43183576142fddc5\``);
        await queryRunner.query(`ALTER TABLE \`metricas_usuario\` DROP FOREIGN KEY \`FK_999f6cf6d7f32b70bed76877eb0\``);
        await queryRunner.query(`ALTER TABLE \`perda\` DROP FOREIGN KEY \`FK_67e63d84cb42f0a7b817c8890b5\``);
        await queryRunner.query(`ALTER TABLE \`perda\` DROP FOREIGN KEY \`FK_8a1a5d43b168400bec3070b41d9\``);
        await queryRunner.query(`ALTER TABLE \`perda\` DROP FOREIGN KEY \`FK_1796ebd4e5cc641dfc669a74110\``);
        await queryRunner.query(`ALTER TABLE \`permissao\` DROP FOREIGN KEY \`FK_c0b320e1b0943f7f0996678fecd\``);
        await queryRunner.query(`ALTER TABLE \`transferencia-cliente\` DROP FOREIGN KEY \`FK_02cf22c3bf09af4d9d0e069a7b4\``);
        await queryRunner.query(`ALTER TABLE \`transferencia-cliente\` DROP FOREIGN KEY \`FK_265743ae329bde2b9a2fcc89a73\``);
        await queryRunner.query(`ALTER TABLE \`transferencia-cliente\` DROP FOREIGN KEY \`FK_a7dcfff24a872d32abb3c474cc6\``);
        await queryRunner.query(`ALTER TABLE \`transferencia-cliente\` DROP FOREIGN KEY \`FK_aa1ee04e3254cb73f40bde418e1\``);
        await queryRunner.query(`ALTER TABLE \`venda\` DROP FOREIGN KEY \`FK_fd83d651fb05d24bc1e97c4cff6\``);
        await queryRunner.query(`ALTER TABLE \`venda\` DROP FOREIGN KEY \`FK_15b70438372ffad25249a2c6fec\``);
        await queryRunner.query(`ALTER TABLE \`cliente\` DROP FOREIGN KEY \`FK_b3e53e9c65f1a58088bb28c4dbe\``);
        await queryRunner.query(`ALTER TABLE \`cliente\` DROP FOREIGN KEY \`FK_26eb6132b607fd16d904df0367d\``);
        await queryRunner.query(`ALTER TABLE \`fornecedor\` DROP FOREIGN KEY \`FK_6e18d94ebc5a941f02a63c5c49a\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`nome\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`nome\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`usuario\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`usuario\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`senha\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP INDEX \`IDX_2863682842e688ca198eb25c12\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`usuario\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`DROP INDEX \`IDX_52c649a8d3e70b66cabf774259\` ON \`contato_produtos_produto\``);
        await queryRunner.query(`DROP INDEX \`IDX_9a697c7f2dace62a85557da34f\` ON \`contato_produtos_produto\``);
        await queryRunner.query(`DROP TABLE \`contato_produtos_produto\``);
        await queryRunner.query(`DROP INDEX \`IDX_4056175fea64c465a8785d7789\` ON \`contato_ocorrencias_ocorrencia\``);
        await queryRunner.query(`DROP INDEX \`IDX_7cd69c4ccf4db31b801110a7c4\` ON \`contato_ocorrencias_ocorrencia\``);
        await queryRunner.query(`DROP TABLE \`contato_ocorrencias_ocorrencia\``);
        await queryRunner.query(`DROP INDEX \`IDX_93efba0a2c38d6a4ee0da268cf\` ON \`ocorrencia_flags_ocorrencia-flag\``);
        await queryRunner.query(`DROP INDEX \`IDX_1fa6e78bfb74cfc6ade35d8a2b\` ON \`ocorrencia_flags_ocorrencia-flag\``);
        await queryRunner.query(`DROP TABLE \`ocorrencia_flags_ocorrencia-flag\``);
        await queryRunner.query(`DROP INDEX \`IDX_33871093b92a531e2dd94b973b\` ON \`perda_produtos_produto\``);
        await queryRunner.query(`DROP INDEX \`IDX_d8931ba4b2b0ac61023b6c05a8\` ON \`perda_produtos_produto\``);
        await queryRunner.query(`DROP TABLE \`perda_produtos_produto\``);
        await queryRunner.query(`DROP INDEX \`IDX_8976a3faa1be5c9bad1591c104\` ON \`venda_produtos_produto\``);
        await queryRunner.query(`DROP INDEX \`IDX_54718795de3c5cb781eea09819\` ON \`venda_produtos_produto\``);
        await queryRunner.query(`DROP TABLE \`venda_produtos_produto\``);
        await queryRunner.query(`DROP INDEX \`IDX_9d38fe4f4983383976e86cd2e5\` ON \`cliente_telefones_telefone\``);
        await queryRunner.query(`DROP INDEX \`IDX_d6b14fb9e3c12f9d1add2a806e\` ON \`cliente_telefones_telefone\``);
        await queryRunner.query(`DROP TABLE \`cliente_telefones_telefone\``);
        await queryRunner.query(`DROP INDEX \`IDX_44b282ee52a4ec03f3cb6a9acf\` ON \`cliente_produtos_produto\``);
        await queryRunner.query(`DROP INDEX \`IDX_8cd9bce9e1ac682b4c4f66cd56\` ON \`cliente_produtos_produto\``);
        await queryRunner.query(`DROP TABLE \`cliente_produtos_produto\``);
        await queryRunner.query(`DROP INDEX \`IDX_02315821f911701cc643ddd6bc\` ON \`produto_fornecedores_fornecedor\``);
        await queryRunner.query(`DROP INDEX \`IDX_82dad16f5b419d515e65a69fb6\` ON \`produto_fornecedores_fornecedor\``);
        await queryRunner.query(`DROP TABLE \`produto_fornecedores_fornecedor\``);
        await queryRunner.query(`DROP INDEX \`IDX_f1509cffb191ea48e42ba47e65\` ON \`fornecedor_telefones_telefone\``);
        await queryRunner.query(`DROP INDEX \`IDX_ed9e8389af4c7f0cc00384f81f\` ON \`fornecedor_telefones_telefone\``);
        await queryRunner.query(`DROP TABLE \`fornecedor_telefones_telefone\``);
        await queryRunner.query(`DROP TABLE \`contato\``);
        await queryRunner.query(`DROP TABLE \`agendamento\``);
        await queryRunner.query(`DROP TABLE \`logs\``);
        await queryRunner.query(`DROP INDEX \`usuario-ocorrencia\` ON \`metricas_usuario\``);
        await queryRunner.query(`DROP TABLE \`metricas_usuario\``);
        await queryRunner.query(`DROP INDEX \`IDX_82637440f03498f3c6e241000d\` ON \`ocorrencia\``);
        await queryRunner.query(`DROP TABLE \`ocorrencia\``);
        await queryRunner.query(`DROP TABLE \`ocorrencia-flag\``);
        await queryRunner.query(`DROP TABLE \`perda\``);
        await queryRunner.query(`DROP TABLE \`funil\``);
        await queryRunner.query(`DROP INDEX \`IDX_318d80ec9b2e2c4a7d01552917\` ON \`permissao\``);
        await queryRunner.query(`DROP TABLE \`permissao\``);
        await queryRunner.query(`DROP TABLE \`transferencia-cliente\``);
        await queryRunner.query(`DROP TABLE \`venda\``);
        await queryRunner.query(`DROP INDEX \`REL_b3e53e9c65f1a58088bb28c4db\` ON \`cliente\``);
        await queryRunner.query(`DROP TABLE \`cliente\``);
        await queryRunner.query(`DROP TABLE \`produto\``);
        await queryRunner.query(`DROP INDEX \`REL_6e18d94ebc5a941f02a63c5c49\` ON \`fornecedor\``);
        await queryRunner.query(`DROP TABLE \`fornecedor\``);
        await queryRunner.query(`DROP TABLE \`telefone\``);
        await queryRunner.query(`DROP TABLE \`endereco\``);
    }

}
